import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillMail,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import joseey from "../public/unnamed.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import icon1 from "../public/icon1.jpg";
import icon3 from "../public/icon3.jpg";
import icon4 from "../public/icon4.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import portfolio from "../public/portfolio.png";
import kaawa from "../public/kaawa.png";
import paysoko from "../public/paysoko.png";
import dadasoko from "../public/dadasoko.png";
import coffeeklub from "../public/coffeeklub.png";
import radico from "../public/radico.png";
import Dadamodels from "../public/Dadamodels.png";
import Osirua from "../public/Osirua.png";
import ChamaNet from "../public/ChamaNet.png";
import Plugmtaani from "../public/Plugmtaani.png";
import Plugmtaanifoundation from "../public/Plugmtaanifoundation.png";
import Plugroom from "../public/Plugroom.png";
import logo from "../public/joe1.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Joseey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-20">
        <section className="min-h-screen">
          <nav className="py-8 mb-5 flex justify-between dark:text-white">
            <Image
              className="logo rounded-sm object-cover cursor-pointer"
              // width={"4%"}
              // height={"4%"}
              layout="responsive"
              src={logo}
              alt=""
            />
            {/* <h1 className="font-burtons text-xl">Hi 👋🏾 , I'm Joseey.</h1> */}
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://1drv.ms/b/s!AiKB_OK0HmmpmDrae1205CtlMjIp?e=SqjgpS"
                  target="blank"
                >
                  MY CV.
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-6 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Maruria Joseph
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Front-end Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Accomplished Front-End Developer transitioning to Full-Stack, with
              expertise in React.js, Laravel, and WordPress. Proven ability to
              enhance user engagement and operational efficiency, notably at
              PaySoko Systems and the Kenya Revenue Authority. Passionate about
              delivering user-centric solutions through innovative web
              development.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400 cursor-pointer">
              <a
                href="https://www.linkedin.com/in/joseph-maruria-67226619a/"
                target="blank"
              >
                <AiFillLinkedin />
              </a>
              {/* <a href="https://twitter.com/Joseey23" target="blank">
                <AiFillTwitterCircle />
              </a> */}
              <a href="https://github.com/joseey23" target="blank">
                <AiFillGithub />
              </a>
              <a
                href="https://mail.google.com/mail/?view=cm&source=mailto&to=[josephmaruria@gmail.com]"
                target="blank"
              >
                <AiFillMail />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-90 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={joseey} layout="fill" style="cover" alt="" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">My Expertise</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer a wide range of services such as web design, interface
              design and brand design. These are the different
              <span className="text-teal-500"> skills </span>
              and <span className="text-teal-500">tools </span>i have
              specialised in over the years i have created digital products for
              both business and consumer use.
            </p>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer a wide range of services such as web design, interface design, brand design and software development.
            </p> */}
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={icon1} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Software Development
              </h3>
              <p className="py-2">
                I develop and bring to life projects using a vast variety of the
                latest technology.
              </p>
              <h4 className="py-4 text-teal-600">Development tools</h4>
              <p className="text-gray-800 py-1">Reactjs</p>
              <p className="text-gray-800 py-1">Nextjs</p>
              <p className="text-gray-800 py-1">ReactNative</p>
              <p className="text-gray-800 py-1">TailwindCSS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={icon3} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">UI/UX design</h3>
              <p className="py-2">
                I come up with interactive UI/UX designs for clients.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools </h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={icon4} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Web Development
              </h3>
              <p className="py-2">
                I develop and bring to life web applications based on client's
                design and ideas.
              </p>
              <h4 className="py-4 text-teal-600">Development Tools</h4>
              <p className="text-gray-800 py-1">ReactJS</p>
              <p className="text-gray-800 py-1">HTML&CSS</p>
              <p className="text-gray-800 py-1">Laravel</p>
              <p className="text-gray-800 py-1">WordpressCMS</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Works</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Here are some of the
              <span className="text-teal-500"> past projects </span>I managed to
              come up with over the years. To explore each project, simply click
              on its title to delve into the details.
            </p>
          </div>

          {/* new section */}

          <div className="flex flex-row flex-wrap lg:flex gap-4 lg:gap-0 ">
            {/* 1 Work */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-4 lg:p-10 rounded-xl my-4 lg:my-10  dark:bg-white">
              <a href="https://landing.paysokosystems.com/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={paysoko}
                  alt=""
                />
              </a>
              <a href="https://landing.paysokosystems.com/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2  ">
                  PaySoko Systems Landing Page.
                </h3>
              </a>
            </div>

            {/* #2 Works */}
            <div className="w-full lg:w-1/3 text-center shadow-lg p-4 lg:p-10 rounded-xl my-4 lg:my-10 dark:bg-white">
              <a href="https://landing.dadasoko.com/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={dadasoko}
                  alt=""
                />
              </a>
              <a href="https://landing.dadasoko.com/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  DadaSoko Landing Page.
                </h3>
              </a>
            </div>

            {/* #3 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-4 lg:p-10 rounded-xl my-4 lg:my-10 dark:bg-white">
              <a href="https://chamanet.co.ke/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={ChamaNet}
                  alt=""
                />
              </a>
              <a href="https://chamanet.co.ke/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  {" "}
                  ChamaNet Kenya.{" "}
                </h3>
              </a>
            </div>

            {/* #4 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-4 lg:p-10 rounded-xl my-4 lg:my-10 dark:bg-white">
              <a href="https://plugmtaani.org/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Plugmtaani}
                  alt=""
                />
              </a>
              <a href="https://plugmtaani.org/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Plug Mtaani Business Competition.
                </h3>
              </a>
            </div>

            {/* #5 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-4 lg:p-10 rounded-xl my-4 lg:my-10 dark:bg-white">
              <a href="https://plugmtaanifoundation.org/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Plugmtaanifoundation}
                  alt=""
                />
              </a>
              <a href="https://plugmtaanifoundation.org/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Plug Mtaani Foundation.
                </h3>
              </a>
            </div>

            {/* #6 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-4 lg:p-10 rounded-xl my-4 lg:my-10 dark:bg-white">
              <a href="https://iamradico.org/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={radico}
                  alt=""
                />
              </a>
              <a href="https://iamradico.org/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Radico Kenya.
                </h3>
              </a>
            </div>

            {/* #7 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-4 lg:p-10 rounded-xl my-4 lg:my-10 dark:bg-white">
              <a href="https://osiruabundus.com/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Osirua}
                  alt=""
                />
              </a>
              <a href="https://osiruabundus.com/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Osirua Bundus Rental Vacation Home.
                </h3>
              </a>
            </div>

            {/* #8 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-8 rounded-xl my-10 dark:bg-white">
              <a href="https://room.niplug.com/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Plugroom}
                  alt=""
                />
              </a>
              <a href="https://room.niplug.com/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Plug Room by NiPlug.
                </h3>
              </a>
            </div>

            {/* #9 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-4 lg:p-10 rounded-xl my-4 lg:my-10 dark:bg-white">
              <a href="https://dadamodels.com/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={Dadamodels}
                  alt=""
                />
              </a>
              <a href="https://dadamodels.com/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 "> DadaModels </h3>
              </a>
            </div>

            {/* #10 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-4 lg:p-10 rounded-xl my-4 lg:my-10 dark:bg-white">
              <a href="http://coffeeklub.co.ke/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={coffeeklub}
                  alt=""
                />
              </a>
              <a href="http://coffeeklub.co.ke/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Coffee Klub KE
                </h3>
              </a>
            </div>

            {/* #11 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-4 lg:p-10 rounded-xl my-4 lg:my-10 dark:bg-white">
              <a href="https://sokoverse-beryl.vercel.app" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web1}
                  alt=""
                />
              </a>
              <a href="https://sokoverse-beryl.vercel.app" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  SokoVerse Landing Page
                </h3>
              </a>
            </div>

            {/* #12 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-8 rounded-xl my-10 dark:bg-white">
              <a href="https://paysokosystems.vercel.app/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web2}
                  alt=""
                />
              </a>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                PaySoko Systems UI
              </h3>
            </div>

            {/* #13 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-4 lg:p-10 rounded-xl my-4 lg:my-10 dark:bg-white">
              <a href="https://kaawacoffee.com/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={kaawa}
                  alt=""
                />
              </a>
              <a href="https://kaawacoffee.com/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Kaawa Coffee.
                </h3>
              </a>
            </div>

            {/* #14 Works */}

            <div className="w-full lg:w-1/3 text-center shadow-lg p-8 rounded-xl my-10 dark:bg-white">
              <a href="https://najua-bot.vercel.app/" target="blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web5}
                  alt=""
                />
              </a>
              <a href="https://najua-bot.vercel.app/" target="blank">
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Najua (Open AI Powered Bot)
                </h3>
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
